HotelPatito/Controllers/ContactenosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HotelPatito.Models.Tipadas;

namespace HotelPatito.Controllers
{
    public class ContactenosController : Controller
    {
        private HotelDB db = new HotelDB();

        // GET: Contactenos
        public ActionResult Index()
        {
            return View(db.Hotel.ToList());
        }

        // GET: Contactenos/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotel.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // GET: Contactenos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contactenos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "nombre_Hotel,descripcion_Hotel,sobreNosotros_Hotel,latitud_Hotel,longitud_Hotel,comoLlegar_Hotel,telefono_Hotel,aptoPostal_Hotel,email_Hotel")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                db.Hotel.Add(hotel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hotel);
        }

        // GET: Contactenos/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotel.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // POST: Contactenos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "nombre_Hotel,descripcion_Hotel,sobreNosotros_Hotel,latitud_Hotel,longitud_Hotel,comoLlegar_Hotel,telefono_Hotel,aptoPostal_Hotel,email_Hotel")] Hotel hotel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hotel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hotel);
        }

        // GET: Contactenos/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotel.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // POST: Contactenos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Hotel hotel = db.Hotel.Find(id);
            db.Hotel.Remove(hotel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HotelPatito/Controllers/FacilidadesController.cs
using HotelPatito.Models.Tipadas;
using Newtonsoft.Json;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HotelPatito.Controllers
{
    public class FacilidadesController : Controller
    {
        private string Base_URL = "http://localhost:58406/";
        // GET: Facilidades
        public async Task<ActionResult> Index()
        {

            HttpClient cliente = new HttpClient();
            cliente.BaseAddress = new Uri(Base_URL);
            cliente.DefaultRequestHeaders.Accept.Clear();
            cliente.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

            var respuesta = await cliente.GetStringAsync("Facilidad/ObtenerFacilidades");
            var facilidad = JsonConvert.DeserializeObject<FacilidadesConImagenes>(respuesta);
            return View(facilidad);

           
        }
        public async Task<ActionResult> PaginaUnoFacilidades()
        {
            return View();
        }
        public ActionResult PaginaDosFacilidades()
        {
            ViewBag.Message = "Pagina dos de facilidades";

            return View();
        }
        public ActionResult PaginaTresFacilidades()
        {
            ViewBag.Message = "Pagina tres de facilidades";

            return View();
        }
        public ActionResult PaginaCuatroFacilidades()
        {
            ViewBag.Message = "Pagina cuatro de facilidades";

            return View();
        }
       
    }
}

HotelPatito/Controllers/ReservarController.cs
using HotelPatito.Models.Tipadas;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HotelPatito.Controllers
{
    public class ReservarController : Controller
    {

        private string Base_URL = "http://localhost:58406/";
        // GET: Reservar
        public ActionResult BuscaHabitacion()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> ReservarHabitacion(string fechaLlegada, string fechaSalida, string tipo)
        {
            //System.DateTime fechaInic = DateTime.Parse(fechaLlegada);
            //System.DateTime fechaFin = DateTime.Parse(fechaSalida);

            HttpClient cliente = new HttpClient();
            cliente.BaseAddress = new Uri(Base_URL);
            cliente.DefaultRequestHeaders.Accept.Clear();
            cliente.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

            var respuesta = await cliente.GetStringAsync("Reservacion/HabitacionDisponible?fechaLlegada=" + fechaLlegada + "&fechaSalida=" + fechaSalida + "&tipo=" + tipo);

            var habitacionDisponible = JsonConvert.DeserializeObject<HabitacionDisponible>(respuesta);

            string fechaI = Convert.ToString(habitacionDisponible.fechaInic);
            string fechaF = Convert.ToString(habitacionDisponible.fechaFin);

            var fechainicial = fechaI.Substring(0, 10);

            var fechaFinal = fechaF.Substring(0, 10);

            string[] fechas = new string[2];

            fechas[0] = fechainicial;
            fechas[1] = fechaFinal;

            ViewBag.Message = fechas;

            return View(habitacionDisponible);
        }

        [HttpPost]
        public async Task<ActionResult> CargarDatosCliente(string cedula)
        {

            HttpClient cliente = new HttpClient();
            cliente.BaseAddress = new Uri(Base_URL);
            cliente.DefaultRequestHeaders.Accept.Clear();
            cliente.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

            var respuesta = await cliente.GetStringAsync("Reservacion/CargarDatosCliente?cedula=" + cedula);

            //La variable Cliente debe estar en Tipadas
            var clienteResultante = JsonConvert.DeserializeObject<Cliente>(respuesta);

            string resultado = clienteResultante.nombre_Cliente + "/" +
                               clienteResultante.apellidos_Cliente + "/" +
                               clienteResultante.email_Cliente + "/" +
                               clienteResultante.tarjeta_Cliente;

            if (clienteResultante != null)
            {
                return Json(resultado);
            }
            else
            {
                return Json(null);

            }

            //return Json(clienteResultante);

        }//CargarDatosCliente

        [HttpPost]
        public async Task<ActionResult> HacerReservacion(string fechaLlegada, string fechaSalida, int habitacion, string cedula,
            string nombre, string apellidos, int tarjeta, string email)
        {
            //System.DateTime fechaInic = DateTime.Parse(fechaLlegada);
            //System.DateTime fechaFin = DateTime.Parse(fechaSalida);

            HttpClient cliente = new HttpClient();
            cliente.BaseAddress = new Uri(Base_URL);
            cliente.DefaultRequestHeaders.Accept.Clear();
            cliente.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

            var respuesta = await cliente.GetStringAsync("Reservacion/HacerReservacion?fechaLlegada=" + fechaLlegada + "&fechaSalida=" 
                + fechaSalida + "&habitacion=" + habitacion + "&cedula=" + cedula + "&nombre=" + nombre + "&apellidos=" + apellidos
                + "&tarjeta=" + tarjeta + "&email=" + email);

            var Reservacion = JsonConvert.DeserializeObject<Reservacion>(respuesta);

            try
            {

                MailMessage correo = new MailMessage();
                correo.From = new MailAddress("sergdios09@gmail.com");
                correo.To.Add(email);
                correo.Subject = "Reservacion en Hotel Patito";
                correo.Body = "El siguiente correo es para verificar que el cliente: "+nombre+" "+ apellidos+ 
                    " realizó una reservacion para la habitación número: "+ habitacion+" para la fecha"+fechaLlegada+
                    " hasta la fecha "+ fechaSalida +". Gracias por preferirnos ";
                correo.IsBodyHtml = true;
                correo.Priority = MailPriority.Normal;

                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 25;
                smtp.EnableSsl = true;
                smtp.UseDefaultCredentials = true;
                string sCuentaCorreo = "hotelpatito2018@gmail.com";
                string sPasswordCorreo = "segama701";
                smtp.Credentials = new System.Net.NetworkCredential(sCuentaCorreo, sPasswordCorreo);
                smtp.Send(correo);

                ViewBag.Message = "Se envio correctamente";
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
            }


            //ACA va la cara de tipadas

            ClienteReserva clienteReserva = new ClienteReserva();
            clienteReserva.nombre_cliente = nombre;
            clienteReserva.numero_habitacion = habitacion;
            clienteReserva.mail = email;
            
            return RedirectToAction("Result",clienteReserva);
        }
        // GET: Reservar
        public ActionResult Index()
        {
            return View();
        }

        // GET: Reservar/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Reservar/Details/5
        public ActionResult Result(ClienteReserva cliente)
        {
            return View(cliente);
        }
        // GET: Reservar/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Reservar/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reservar/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Reservar/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reservar/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Reservar/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HotelPatito/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <title>Hotel Patito</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Pooled Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Bootstrap Core CSS -->
    <link href="~/assets/css/bootstrap.min.css" rel='stylesheet' type='text/css' />
    <!-- Custom CSS -->
    <link href="~/assets/css/style.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="~/assets/css/morris.css" type="text/css" />
    <!-- Graph CSS -->
    <link href="~/assets/css/font-awesome.css" rel="stylesheet">
    <!-- jQuery -->
    <script src="~/assets/js/jquery-2.1.4.min.js"></script>
    <!-- //jQuery -->
    <link href='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400' rel='stylesheet' type='text/css' />
    <link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
    <!-- lined-icons -->
    <link rel="stylesheet" href="~/assets/css/icon-font.min.css" type='text/css' />


</head>
<body>
    <div class="page-container">
        <!--/content-inner-->
        <div class="left-content">
            <div class="mother-grid-inner">
                <div class="header-main">
                    <div class="logo-w3-agile">
                        <img style="width:150px; height:150px" src="~/images/Logo 2.PNG">
                    </div>
                    <div class="">

                        <!--search-box-->
                        <div class="w3layouts-left" style="width:540px; text-align:center;">
                            <!--search-box-->
                            <div class="w3-search-box" style="text-align:center; width:500px">
                                <h1 style="color:white">HOTEL PATITO</h1>
                            </div><!--//end-search-box-->
                            <div class="clearfix"> </div>

                        </div>
                        <div class="clearfix"> </div>
                    </div>



                    <div class="clearfix"> </div>

                </div>
                <br />
                <!--heder end here-->
                <!--//four-grids here-->
                <!--agileinfo-grap-->
                <div class="agileinfo-grap">
                    <div class="agileits-box">
                        <header class="agileits-box-header clearfix"></header>
                        @RenderBody()


                    </div>
                </div>
                <!--//agileinfo-grap-->
                <!--photoday-section-->
                <!--//photoday-section-->
                <!--w3-agileits-pane-->
                <br />
                <br />
                <!--//w3-agileits-pane-->
                <!-- script-for sticky-nav -->
                <script>
                    $(document).ready(function () {
                        var navoffeset = $(".header-main").offset().top;
                        $(window).scroll(function () {
                            var scrollpos = $(window).scrollTop();
                            if (scrollpos >= navoffeset) {
                                $(".header-main").addClass("fixed");
                            } else {
                                $(".header-main").removeClass("fixed");
                            }
                        });

                    });
                </script>
                <!-- /script-for sticky-nav -->
                <!--inner block start here-->
                <div class="inner-block">

                </div>
                <!--inner block end here-->
                <!--copy rights start here-->
                <div class="copyrights">
                    <p>© 2018 Hotel Patito. All Rights Reserved </p>
                </div>
                <!--COPY rights end here-->
            </div>
        </div>
        <!--//content-inner-->
        <!--/sidebar-menu-->
        <div class="sidebar-menu">
            <header class="logo1">
                <a href="#" class="sidebar-icon"> <span class="fa fa-bars"></span> </a>
            </header>
            <div style="border-top:1px ridge rgba(255, 255, 255, 0.15)"></div>
            <div class="menu">
                <ul id="menu">

                    <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-tachometer"></i> <span>Home</span><div class="clearfix"></div></a></li>
                    <li id="menu-academico"><a href="@Url.Action("About", "Home")"><i class="fa fa-picture-o"></i><span>Sobre Nosotros</span><div class="clearfix"></div></a></li>
                    @*<li id="menu-academico"><a href="@Url.Action("Index", "Home")"><i class="fa fa-envelope nav_icon"></i><span>Create admin (prueba)</span><div class="clearfix"></div></a></li>*@
                    <li><a href="@Url.Action("Index", "Facilidades")"><i class="fa fa-bar-chart" aria-hidden="true"></i><span>Facilidades</span><div class="clearfix"></div></a></li>
                    @*<li><a href="@Url.Action("PaginaUnoFacilidades", "Facilidades")"><i class="fa fa-picture-o" aria-hidden="true"></i><span>Facilidades</span><div class="clearfix"></div></a></li>*@
                    <li id="menu-academico"><a href="@Url.Action("Index", "Contactenos")"><i class="fa fa-envelope nav_icon"></i><span>Contactenos</span><div class="clearfix"></div></a></li>
                    @*<li id="menu-academico"><a href="@Url.Action("Index", "Home")"><i class="fa fa-bar-chart"></i><span>Contactenos</span><div class="clearfix"></div></a></li>*@
                    <li id="menu-academico"><a href="@Url.Action("Tarifas", "Home")"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i><span>Tarifas</span><div class="clearfix"></div></a></li>
                    <li><a href="@Url.Action("BuscaHabitacion", "Reservar")"><i class="fa fa-table"></i>  <span>Reservar en linea</span><div class="clearfix"></div></a></li>
                    <li><a href="@Url.Action("ComoLlegar", "Home")"><i class="fa fa-map-marker" aria-hidden="true"></i>  <span>Como Llegar?</span><div class="clearfix"></div></a></li>
                    <li><a href="@Url.Action("Create", "Administrador", new { login = true })"><i class="fa fa-map-marker" aria-hidden="true"></i>  <span>Iniciar sesion</span><div class="clearfix"></div></a></li>
                </ul>

                <div id="myCarousel" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#myCarousel" data-slide-to="1"></li>
                        <li data-target="#myCarousel" data-slide-to="2"></li>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">

                        <div class="item active">
                            <a href="https://www.google.com">
                                <img src="~/images/1.jpg" alt="Los Angeles" style="width:100%;height:100px;">
                            </a>
                            <div class="carousel-caption">

                            </div>
                        </div>

                        <div class="item">
                            <a href="https://www.google.com">

                                <img src="~/images/2.jpg" alt="Chicago" style="width:100%;height:100px;">
                            </a>
                            <div class="carousel-caption">
                            </div>
                        </div>

                        <div class="item">
                            <a href="https://www.google.com">

                                <img src="~/images/3.jpg" alt="New York" style="width:100%;height:100px;">
                            </a>
                            <div class="carousel-caption">

                            </div>
                        </div>

                    </div>

                    <!-- Left and right controls -->
                    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#myCarousel" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <script>

                    var toggle = true;

                    $(".sidebar-icon").click(function () {
                        if (toggle) {
                            $(".page-container").addClass("sidebar-collapsed").removeClass("sidebar-collapsed-back");
                            $("#menu span").css({ "position": "absolute" });
                        }
                        else {
                            $(".page-container").removeClass("sidebar-collapsed").addClass("sidebar-collapsed-back");
                            setTimeout(function () {
                                $("#menu span").css({ "position": "relative" });
                            }, 400);
                        }

                        toggle = !toggle;
                    });

                </script>

                <!--js -->
                <script src="~/assets/js/jquery.nicescroll.js"></script>
                <script src="~/assets/js/scripts.js"></script>
                <!-- Bootstrap Core JavaScript -->
                <script src="~/assets/js/bootstrap.min.js"></script>
                <!-- /Bootstrap Core JavaScript -->
                <!-- morris JavaScript -->
                <script src="~/assets/js/raphael-min.js"></script>
                <script src="~/assets/js/morris.js"></script>
                
                @RenderSection("scripts", required: false)


</body>
</html>